       IDENTIFICATION DIVISION.
       PROGRAM-ID. IDSAMPLE.
       ENVIRONMENT DIVISION.
       PROCEDURE DIVISION.
           DISPLAY 'HELLO WORLD'.
           DISPLAY 'HELLO IKAN from GT'.
           DISPLAY 'Jenkin tetsing123456'.   
           STOP RUN.
